runtime: nodejs10
service: ar-video-conf-demo
# entrypoint: serve -l 8080 -s build

instance_class: F2

# env_variables:
#   PORT: 8080

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_dir: build